# Generated by Django 4.2.27 on 2026-01-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeshWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('destination_address', models.CharField(db_index=True, max_length=128)),
                ('token', models.CharField(max_length=16)),
                ('chain', models.CharField(max_length=32)),
                ('source_provider', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=128)),
                ('history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mesh Webhook',
                'verbose_name_plural': 'Mesh Webhooks',
                'db_table': 'meshsbox_webhook',
                'ordering': ['-updated_at'],
            },
        ),
    ]
