# Generated by Django 4.2.27 on 2026-01-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshsbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(db_index=True, max_length=255)),
                ('integration_type', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('wallet_address', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('scope', models.CharField(default='read', max_length=16)),
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('lang', models.CharField(default='en', max_length=8)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Token',
                'verbose_name_plural': 'Integration Tokens',
                'db_table': 'integration_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='integrationtoken',
            constraint=models.UniqueConstraint(fields=('token_id', 'integration_type'), name='unique_token_type'),
        ),
    ]
