# Generated by Django 5.2.10 on 2026-01-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshsbox', '0002_integrationtoken_integrationtoken_unique_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationtoken',
            name='token_id',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
